version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 1000
  argument-count:
    config:
      threshold: 6
  method-count:
    enabled: false
  complex-logic:
    config:
      threshold: 10
