repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ".*(data.*|extern.*|licenses.*|_parsetab.py)$"
    - id: fix-encoding-pragma
      exclude: ".*(data.*|extern.*|licenses.*|_parsetab.py|test_cds.py)$"
    - id: trailing-whitespace
      exclude: ".*(data.*|extern.*|licenses.*|_parsetab.py|test_cds.py)$"

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: python-no-eval
    - id: python-no-log-warn
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.2
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shfmt

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort
      additional_dependencies: ["toml"]

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      additional_dependencies: ["toml"]

# We list the warnings/errors to check for here rather than in setup.cfg because
# we don't want these options to apply whenever anyone calls flake8 from the
# command-line or their code editor - in this case all warnings/errors should be
# checked for. The warnings/errors we check for here are:
# E101 - mix of tabs and spaces
# W191 - use of tabs
# E201 - whitespace after '('
# E202 - whitespace before ')'
# W291 - trailing whitespace
# W292 - no newline at end of file
# W293 - trailing whitespace
# W391 - blank line at end of file
# E111 - 4 spaces per indentation level
# E112 - 4 spaces per indentation level
# E113 - 4 spaces per indentation level
# E301 - expected 1 blank line, found 0
# E302 - expected 2 blank lines, found 0
# E303 - too many blank lines (3)
# E304 - blank lines found after function decorator
# E305 - expected 2 blank lines after class or function definition
# E306 - expected 1 blank line before a nested definition
# E502 - the backslash is redundant between brackets
# E722 - do not use bare except
# E901 - SyntaxError or IndentationError
# E902 - IOError
# E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
# F822: undefined name in __all__
# F823: local variable name referenced before assignment
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ['--count', '--select', 'E101,W191,E201,E202,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823']
      exclude: ".*(data.*|extern.*|cextern)$"

- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.6
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--nbqa-mutate]
    - id: nbqa-flake8
      additional_dependencies: [flake8==3.8.4]
      args:
        - "--nbqa-mutate"
        - "--max-line-length=100"
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
      args: [--nbqa-mutate, --py36-plus]
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
      args: [--nbqa-mutate]
