[project]
name = "interpolated_coordinates"
description = "Univariate Interpolations of Astropy Coordinates"
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE.rst"}
keywords = ["interpolate", "interpolation", "coordinates", "astronomy"]
authors = [
    {name = "Nathaniel Starkman"}
]
maintainers = [
    {name = "nathaniel Starkman"}
]
classifiers = [
  "Programming Language :: Python"
]
dependencies = [
    "astropy",
    "numpy",
    "scipy",
]
edit_on_github = "False"


[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "extension_helpers",
            "wheel"]

build-backend = 'setuptools.build_meta'


[project.optional-dependencies]
test = [
  "matplotlib",
  "pytest",
  "pytest-astropy",
]
docs = [
  "graphviz",
  "matplotlib",
  "sphinx-astropy",
  "sphinx",
  "pytest",
]

[project.urls]
repository = "https://github.com/nstarman/interpolated-coordinates"
documentation = "https://github.com/nstarman/interpolated-coordinates"


[tool.autopep8]
max_line_length = 100
in-place = true
recursive = true


[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "LOCALFOLDER"]
known_localfolder = "interpolated_coordinates"
known_third_party = ["astropy", "matplotlib", "numpy", "pytest", "scipy", "setuptools"]
import_heading_stdlib = "STDLIB"
import_heading_thirdparty = "THIRD PARTY"
import_heading_localfolder = "LOCAL"


[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
exclude = '''(?x)(
    (^|/)tests/
    |conftest\.py$
)'''

[tool.pytest.ini_options]
testpaths = [
    "interpolated_coordinates",
    "docs",
]
astropy_header = "True"
doctest_plus = "enabled"
text_file_format = "rst"
addopts = "--doctest-rst"


[tool.setuptools_scm]
write_to = "interpolated_coordinates/_version.py"
