# GitHub Actions workflow that runs on a cron schedule.

name: Cron Scheduled CI Tests

on:
  schedule:
    # run at 6am UTC on Mondays
    - cron: '0 6 * * 1'
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled

env:
  IS_CRON: 'true'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: (github.repository == 'interpolated_coordinates/interpolated_coordinates' && (github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'Extra CI')))
    env:
      ARCH_ON_CI: "normal"
    strategy:
      fail-fast: false
      matrix:
        include:

          # We check numpy-dev also in a job that only runs from cron, so that
          # we can spot issues sooner. We do not use remote data here, since
          # that gives too many false positives due to URL timeouts. We also
          # install all dependencies via pip here so we pick up the latest
          # releases.
          - name: Python 3.10 with dev version of key dependencies
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-test-devdeps

          - name: Documentation link check
            os: ubuntu-latest
            python: 3.8
            toxenv: linkcheck

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-de and tzdata
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-de tzdata
    - name: Install graphviz
      if: ${{ matrix.toxenv == 'linkcheck' }}
      run: sudo apt-get install graphviz
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs}} -e ${{ matrix.toxenv}} -- ${{ matrix.toxposargs}}
