name: "When Opened"

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    # NOTE: sync-labels due to https://github.com/actions/labeler/issues/112
    - name: Label PR
      uses: actions/labeler@v3
      if: github.event_name == 'pull_request_target'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''
    - name: Greet new contributors
      uses: actions/first-interaction@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: >
            Welcome to interpolated-coordinates 👋 and thank you for your first issue!


            A project member will respond to you as soon as possible.


            GitHub issues in the interpolated-coordinates repository are used
            to track bug reports and feature requests; If your issue poses a
            question about how to use interpolated-coordinates, please instead
            raise your question in [GitHub Discussion](https://github.com/GalOrrery/interpolated-coordinates/discussions).
        pr-message: >
            Welcome to Astropy 👋 and congratulations on your first pull
            request! 🎉


            A project member will respond to you as soon as possible.
    - name: 'Comment Draft PR'
      uses: actions/github-script@v3
      if: github.event.pull_request.draft == true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thank you for your draft pull request! Do you know that you can use `[ci skip]` or `[skip ci]` in your commit messages to skip running continuous integration tests until you are ready?'
          })
